developed the new website under the name "thebull"
ImBIOS/qwiktober-2022 pull request #94
Opened 2022-10-10 03:35 UTC by sandipswain

Closes # 

## 📑 Description

## ✅ Checks

- [✅] My pull request adheres to the code style of this project
- [✅] My code requires changes to the documentation
- [✅] I have updated the documentation as required
- [✅] All the tests have passed

## ℹ Additional Information

2022-10-10 07:14 UTC, rodhisz approved these changes
cool

2022-10-10 07:32 UTC, ImBIOS requested changes
Please replace or remove these files

2022-10-10 07:32 UTC, ImBIOS commented on public/websites/thebull/index.html
> +            <img src="../../images/mail.svg" alt="mail">
don't add file outside your web folder

2022-10-11 01:51 UTC, ImBIOS approved these changes
LGTM!

2022-10-11 01:51 UTC, merged